// GENERATED by tools/phosphor_symbols.py — do not edit by hand.
// Re-run that script to add, remove or re-weight an icon.

import SwiftUI

// §5 — the icon substrate is **Phosphor** (ratified by Ellen on the
// wave-5 build: "Use phosphor"). Every glyph the app draws comes from
// this enum, and every glyph in this enum is a custom SF Symbol compiled
// from Phosphor's MIT-licensed artwork by tools/phosphor_symbols.py.
//
// The symbols are real `.symbolset`s, not images, so §5.4's criterion 3
// holds: Dynamic Type, `.imageScale`, `.font()`, baseline alignment in a
// label run, weight response and `symbolRenderingMode` all behave exactly
// as they did under SF Symbols. `uiGlyph()` is unchanged and still the one
// place I2/I4 are decided.
//
// **This enum is the whole surface.** No call site names an asset string,
// so swapping an icon — or the whole set again — is a one-line change here
// plus a re-run of the generator.
// `CaseIterable` is not decoration: IconCatalogTests walks `allCases`
// so a newly generated icon is covered by the bundle tripwire automatically.
enum Icon: String, CaseIterable {
    /// Phosphor `archive` (regular) — was `archivebox`.
    case archive             = "ph.archive"
    /// Phosphor `arrow-circle-right` (regular) — was `arrow.right.circle`.
    case arrowCircleRight    = "ph.arrow-circle-right"
    /// Phosphor `arrow-clockwise` (regular) — was `arrow.clockwise`.
    case arrowClockwise      = "ph.arrow-clockwise"
    /// Phosphor `arrows-clockwise` (regular) — was `arrow.triangle.2.circlepath`.
    case arrowsClockwise     = "ph.arrows-clockwise"
    /// Phosphor `bookmark` (regular) — was `bookmark`.
    case bookmark            = "ph.bookmark"
    /// Phosphor `books` (regular) — was `books.vertical`.
    case books               = "ph.books"
    /// Phosphor `caret-left` (regular) — was `chevron.left`.
    case caretLeft           = "ph.caret-left"
    /// Phosphor `caret-right` (regular) — was `chevron.right`.
    case caretRight          = "ph.caret-right"
    /// Phosphor `chats` (regular) — was `bubble.left.and.bubble.right`.
    case chats               = "ph.chats"
    /// Phosphor `check` (regular) — was `checkmark`.
    case check               = "ph.check"
    /// Phosphor `check-circle` (regular) — was `checkmark.circle`.
    case checkCircle         = "ph.check-circle"
    /// Phosphor `check-circle` (fill) — was `checkmark.circle.fill`.
    case checkCircleFill     = "ph.check-circle.fill"
    /// Phosphor `circle` (regular) — was `circle`.
    case circle              = "ph.circle"
    /// Phosphor `circle-dashed` (regular) — was `circle.dashed`.
    case circleDashed        = "ph.circle-dashed"
    /// Phosphor `compass` (regular) — was `safari`.
    case compass             = "ph.compass"
    /// Phosphor `dots-three` (regular) — was `ellipsis`.
    case dotsThree           = "ph.dots-three"
    /// Phosphor `download-simple` (regular) — was `square.and.arrow.down`.
    case downloadSimple      = "ph.download-simple"
    /// Phosphor `export` (regular) — was `square.and.arrow.up`.
    case export              = "ph.export"
    /// Phosphor `fast-forward` (fill) — was `forward.fill`.
    case fastForwardFill     = "ph.fast-forward.fill"
    /// Phosphor `gear` (regular) — was `gearshape`.
    case gear                = "ph.gear"
    /// Phosphor `highlighter` (regular) — was `highlighter`.
    case highlighter         = "ph.highlighter"
    /// Phosphor `identification-badge` (regular) — was `person.badge.key`.
    case identificationBadge = "ph.identification-badge"
    /// Phosphor `link` (regular) — was `link`.
    case link                = "ph.link"
    /// Phosphor `list-checks` (regular) — was `checklist`.
    case listChecks          = "ph.list-checks"
    /// Phosphor `lock` (fill) — was `lock.fill`.
    case lockFill            = "ph.lock.fill"
    /// Phosphor `magnifying-glass` (regular) — was `magnifyingglass`.
    case magnifyingGlass     = "ph.magnifying-glass"
    /// Phosphor `pause` (fill) — was `pause.fill`.
    case pauseFill           = "ph.pause.fill"
    /// Phosphor `image` (regular) — was `photo`.
    case photo               = "ph.image"
    /// Phosphor `play-circle` (regular) — was `play.rectangle`.
    case playCircle          = "ph.play-circle"
    /// Phosphor `play` (fill) — was `play.fill`.
    case playFill            = "ph.play.fill"
    /// Phosphor `plus` (regular) — was `plus`.
    case plus                = "ph.plus"
    /// Phosphor `rewind` (fill) — was `backward.fill`.
    case rewindFill          = "ph.rewind.fill"
    /// Phosphor `stop` (fill) — was `stop.fill`.
    case stopFill            = "ph.stop.fill"
    /// Phosphor `tag` (fill) — was `tag.fill`.
    case tagFill             = "ph.tag.fill"
    /// Phosphor `text-aa` (regular) — was `textformat.size`.
    case textAa              = "ph.text-aa"
    /// Phosphor `trash` (regular) — was `trash`.
    case trash               = "ph.trash"
    /// Phosphor `tray` (regular) — was `tray / tray.full`.
    case tray                = "ph.tray"
    /// Phosphor `user-circle` (regular) — was `person.crop.circle`.
    case userCircle          = "ph.user-circle"
    /// Phosphor `users-three` (regular) — was `person.2.slash`.
    case usersThree          = "ph.users-three"
    /// Phosphor `warning` (regular) — was `exclamationmark.triangle`.
    case warning             = "ph.warning"
    /// Phosphor `wifi-slash` (regular) — was `wifi.exclamationmark`.
    case wifiSlash           = "ph.wifi-slash"
    /// Phosphor `x-circle` (fill) — was `xmark.circle.fill`.
    case xCircleFill         = "ph.x-circle.fill"
    /// Phosphor `x` (regular) — was `xmark`.
    case xMark               = "ph.x"
}

extension Image {
    /// The only way an icon enters the app (§5, I1).
    init(_ icon: Icon) {
        self.init(icon.rawValue)
    }
}

/// `Label`'s own generic parameter is called `Icon`, which shadows the enum
/// inside the extension below. This alias is how the initialiser still names it.
typealias IconName = Icon

extension Label where Title == Text, Icon == Image {
    /// `Label("Delete", icon: .trash)` — the Phosphor counterpart of
    /// `Label(_:systemImage:)`, used by menus, swipe actions and list rows.
    init(_ titleKey: LocalizedStringKey, icon: IconName) {
        self.init(titleKey, image: icon.rawValue)
    }

    init(_ title: some StringProtocol, icon: IconName) {
        self.init(title, image: icon.rawValue)
    }
}
